name: Docker Image CI

on:
  push:
    branches: [ "refactoring" ]
  pull_request:
    branches: [ "refactoring" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t algos-datastructures:version0.1 .
